version: '3'

services:
  database:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: locking-user
      POSTGRES_PASSWORD: locking-password
      POSTGRES_DB: locking-db

  redis:
    image: redis:5.0.6-alpine
    restart: always

  app:
    build: .
    environment:
      spring.datasource.url: "jdbc:postgresql://database:5432/locking-db"
      spring.datasource.username: locking-user
      spring.datasource.password: locking-password
      redis.url: "redis://redis:6379"
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis